#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""backtest_report — 產生 backtest_v3_report.html（深色自適應、手機可讀）
用法：python3 backtest_report.py [--open]
"""

import json
import math
import os
import subprocess
import sys

HOME = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HOME, "backtest_v3_report.html")
GN = {"539": "今彩539", "f5": "Fantasy 5", "m6": "六合彩"}

CSS = """
:root{--bg:#f6f7f9;--card:#fff;--fg:#1a1d21;--mut:#5c6570;--line:#e3e6ea;
--ok:#0a7d40;--bad:#c2262e;--warn:#9a6400;--accent:#2a5fd6;--code:#f0f2f5}
@media (prefers-color-scheme:dark){:root:not([data-theme=light]){
--bg:#14171a;--card:#1c2024;--fg:#e6e9ec;--mut:#9aa4ae;--line:#2c3238;
--ok:#4ec27f;--bad:#ff6b6b;--warn:#e0a33a;--accent:#6f9cf5;--code:#22272c}}
:root[data-theme=dark]{--bg:#14171a;--card:#1c2024;--fg:#e6e9ec;--mut:#9aa4ae;
--line:#2c3238;--ok:#4ec27f;--bad:#ff6b6b;--warn:#e0a33a;--accent:#6f9cf5;--code:#22272c}
*{box-sizing:border-box}
body{margin:0;padding:20px 14px 60px;background:var(--bg);color:var(--fg);
font:15px/1.65 -apple-system,"PingFang TC","Helvetica Neue",sans-serif}
.wrap{max-width:940px;margin:0 auto}
h1{font-size:23px;margin:0 0 4px}
h2{font-size:18px;margin:32px 0 10px;padding-top:14px;border-top:1px solid var(--line)}
h3{font-size:15px;margin:20px 0 8px;color:var(--mut)}
.sub{color:var(--mut);font-size:13px;margin-bottom:18px}
.card{background:var(--card);border:1px solid var(--line);border-radius:10px;
padding:14px 16px;margin:12px 0}
.tag{display:inline-block;padding:1px 8px;border-radius:99px;font-size:12px;
font-weight:600;white-space:nowrap}
.t-ok{background:rgba(78,194,127,.16);color:var(--ok)}
.t-bad{background:rgba(255,107,107,.16);color:var(--bad)}
.t-warn{background:rgba(224,163,58,.16);color:var(--warn)}
.scroll{overflow-x:auto;-webkit-overflow-scrolling:touch;margin:10px 0}
table{border-collapse:collapse;width:100%;font-size:13.5px;min-width:520px}
th,td{padding:7px 10px;text-align:right;border-bottom:1px solid var(--line);
white-space:nowrap}
th:first-child,td:first-child{text-align:left}
th{color:var(--mut);font-weight:600;font-size:12.5px}
tr.hl td{background:rgba(111,156,245,.09)}
.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12.5px}
.big{font-size:15px;font-weight:600}
.note{background:var(--code);border-left:3px solid var(--accent);
padding:10px 13px;border-radius:0 7px 7px 0;margin:12px 0;font-size:13.5px}
.warnbox{background:rgba(224,163,58,.1);border-left:3px solid var(--warn);
padding:10px 13px;border-radius:0 7px 7px 0;margin:12px 0;font-size:13.5px}
ul{padding-left:20px;margin:8px 0}li{margin:4px 0}
.foot{color:var(--mut);font-size:12px;margin-top:36px;border-top:1px solid var(--line);
padding-top:12px}
"""


def pct(x):
    return "—" if x is None else f"{x*100:.2f}%"


def pf(p):
    if p is None:
        return "—"
    return "&lt;0.0001" if p < 0.0001 else f"{p:.4f}"


def build():
    st = json.load(open(os.path.join(HOME, "backtest_v3_stats.json"), encoding="utf-8"))
    dg = json.load(open(os.path.join(HOME, "backtest_v3_diagnostics.json"), encoding="utf-8"))
    adj = st["holm"]["adjusted"]
    h = []
    A = h.append

    A(f'<!-- generated by backtest_report.py -->')
    A('<div class="wrap">')
    A('<h1>sfg-v3 / fpx-v3 全歷史回測報告</h1>')
    A('<div class="sub">依 <span class="mono">BACKTEST_REGISTRY.md</span>（2026-08-16 事前註冊）執行'
      f'　·　Holm-Bonferroni 校正，共 {st["holm"]["nTests"]} 次檢定，α=0.05</div>')

    # 誠實界定
    A('<div class="warnbox"><b>本報告能與不能回答什麼</b><br>'
      '<b>不能</b>回答「這樣選會不會比較容易中」——選號不改變中獎機率，這是數學事實。'
      '本回測是<b>除錯與品管工具</b>，不是績效證明。<br>'
      '<b>能</b>回答：過濾規則有沒有副作用、排除區有沒有作用、號碼分佈有沒有被系統性扭曲。</div>')

    # 結論
    A('<h2>結論</h2>')
    A('<div class="card"><ul>')
    A('<li><b>過濾規則沒有扣分</b>（T1，六個檢定全部不顯著）→ sfg-v3 可安心續用。</li>')
    A('<li><b>排除區沒有預測價值</b>（T3 全部不顯著）→ 與 <span class="mono">pick_engine.py</span> '
      '自己預先寫下的預期一致。</li>')
    A('<li><b>fpx-v3 正在無聲失效</b>：長窗下 539/F5/六合 分別有 93%/97%/87% 的期數排除區為空。'
      'fpx-v4（相對門檻）可修好穩定性，但因排除區本無預測價值，<b>修它不會提升命中率</b>。</li>')
    A('<li>兩個顯著結果經追查：一個是 PRNG 路徑偶然（T2），一個是 G3 規則的設計後果（T4）。'
      '<b>沒有發現任何 bug，也沒有發現任何規律。</b></li>')
    A('</ul></div>')

    # 資料
    A('<h2>資料與對照線</h2>')
    A('<div class="scroll"><table><tr><th>彩種</th><th>可評估期數</th><th>歷史窗</th>'
      '<th>每期理論命中</th></tr>')
    for g in ("539", "f5", "m6"):
        a = st["games"][g]
        A(f'<tr><td>{GN[g]}</td><td>{a["nPeriods"]}</td>'
          f'<td>{a["histLen"]["min"]}~{a["histLen"]["max"]} 期</td>'
          f'<td>{a["theory"]["perPeriod"]:.4f}</td></tr>')
    A('</table></div>')
    A('<div class="note">🔴 <b>六合彩有兩個不同口徑，不可混用</b>（2026-08-16 鈞洋澄清）：'
      '<br>・<b>兌獎</b>：特別號<b>不計</b>，只對主 6 碼（與產線一致，維持不動）'
      '→ 用於 T1／T2／T5，理論單碼 6/49 = 12.24%'
      '<br>・<b>「有沒有出現」</b>：特別號<b>要計</b>，主 6 ＋ 特碼共 7 碼'
      '→ 用於不出牌／排除區命中判定（T3），理論 7/49 = 14.29%'
      '<br>※ 排除區／平坦度的 <span class="mono">dist／gaps</span> 只吃主 6 碼；'
      'sfg-v4 廢除排除區後，產線已無處使用「出現」口徑，此處僅為解讀歷史紀錄而保留。</div>')
    A('<div class="note"><b>五條對照線</b>　'
      '<b>S3</b>=現行制度（sfg-v3＋fpx-v3）｜<b>S4</b>=sfg-v3＋fpx-v4（相對門檻）｜'
      '<b>B2</b>=無排除區｜<b>B1</b>=<u>同種子同數列但關閉全部過濾規則</u>｜<b>B0</b>=理論值<br>'
      'B1 是核心對照：與 S 共享 PRNG，<b>S−B1 ＝ 過濾規則的淨效果</b>。</div>')

    # 主結果
    A('<h2>每期平均命中碼數（12 碼中）</h2>')
    A('<div class="scroll"><table><tr><th>彩種</th><th>理論</th><th>S3</th><th>S4</th>'
      '<th>B2</th><th>B1</th><th>S3 三碼全中</th></tr>')
    for g in ("539", "f5", "m6"):
        a = st["games"][g]
        th = a["theory"]["perPeriod"]
        cells = "".join(
            f'<td>{a["totals"][t]["perPeriod"]:.4f}<br>'
            f'<span class="mono" style="color:var(--mut)">'
            f'{(a["totals"][t]["perPeriod"]/th-1)*100:+.2f}%</span></td>'
            for t in ("S3", "S4", "B2", "B1"))
        A(f'<tr><td>{GN[g]}</td><td>{th:.4f}</td>{cells}'
          f'<td>{a["jackpot"]["S3"]} 次</td></tr>')
    A('</table></div>')

    # 檢定
    A('<h2>檢定結果</h2>')
    for g in ("539", "f5", "m6"):
        a = st["games"][g]
        A(f'<h3>{GN[g]}</h3><div class="scroll"><table>'
          '<tr><th>檢定</th><th>統計量</th><th>p</th><th>p (Holm)</th><th>結論</th></tr>')
        rows = [
            ("T1　S3 vs B1（規則淨效果）", "T1_S3_vs_B1", "mean"),
            ("T1　S4 vs B1", "T1_S4_vs_B1", "mean"),
            ("T2　S3 vs B2（fpx-v3 淨效果）", "T2_S3_vs_B2", "mean"),
            ("T2　S4 vs B2（fpx-v4 淨效果）", "T2_S4_vs_B2", "mean"),
            ("T3　排除區命中率 v3", "T3_S3", "binom"),
            ("T3　排除區命中率 v4", "T3_S4", "binom"),
            ("T4　號碼均勻度 v3", "T4_S3", "chi"),
            ("T4　號碼均勻度（對照 B1 無規則）", "T4_B1", "chi"),
            ("T5　命中數分佈 v3", "T5_S3", "chi"),
        ]
        for label, key, kind in rows:
            r = a[key]
            k = f"{g}:{key}"
            has = k in adj
            sig = adj[k]["reject"] if has else False
            padj = pf(adj[k]["pAdj"]) if has else "（未納入校正）"
            if kind == "mean":
                stat = f'均差 {r["meanDiff"]:+.4f}'
            elif kind == "binom":
                stat = (f'{r["x"]}/{r["n"]} = {pct(r["rate"])}<br>'
                        f'<span class="mono" style="color:var(--mut)">理論 {pct(r["p0"])}</span>'
                        if r["n"] else "排除區恆空")
            else:
                stat = f'χ²={r["stat"]:.1f} df={r["df"]}'
            tag = ('<span class="tag t-bad">顯著</span>' if sig
                   else '<span class="tag t-ok">不顯著</span>')
            cls = ' class="hl"' if sig else ''
            A(f'<tr{cls}><td>{label}</td><td>{stat}</td><td class="mono">{pf(r.get("p"))}</td>'
              f'<td class="mono">{padj}</td><td>{tag}</td></tr>')
        A('</table></div>')

    # 追查
    A('<h2>兩個顯著結果的追查</h2>')
    A('<div class="note">REGISTRY §5 事前承諾：「T1 顯著<b>正向</b> → 🚨 不改制度，'
      '先假設程式有 bug」。以下為執行該條款的結果，'
      '腳本 <span class="mono">backtest_diagnostics.py</span> 可複驗。</div>')

    A('<h3>① T2（539）顯著 → 判定為 PRNG 路徑偶然，非因果效果</h3>')
    A('<div class="card">S3 與 B2 的候選池不同 ⇒ PRNG 路徑不同 ⇒ 選出的是<b>兩組完全不同的號碼</b>。'
      '若排除區真有因果效果，換任何 salt 都該同方向。實測換 20 個 salt：</div>')
    A('<div class="scroll"><table><tr><th>彩種</th><th>真實均差</th>'
      '<th>20 salt 分佈</th><th>產線 salt 排名</th><th>安慰劑檢定 z</th></tr>')
    for g in ("539", "f5", "m6"):
        d = dg[g]
        s, p = d["D2_salt"], d["D1_placebo"]
        rank_tag = ('<span class="tag t-warn">第 %d/%d</span>' % (s["rank"], s["n"])
                    if s["rank"] == 1 else "第 %d/%d" % (s["rank"], s["n"]))
        A(f'<tr><td>{GN[g]}</td><td class="mono">{d["realMeanDiff"]:+.5f}</td>'
          f'<td class="mono">{s["mean"]:+.5f} ± {s["sd"]:.5f}</td>'
          f'<td>{rank_tag}</td><td class="mono">{p["z"]:+.2f}</td></tr>')
    A('</table></div>')
    A('<div class="card"><b>判定</b>：20 個 salt 的均差分佈<b>以 0 為中心</b>'
      '（539 為 +0.00046 ± 0.00264），產線 salt 在三彩種的排名分別是 '
      '<b>1 / 11 / 11</b> —— 隨機散佈。539 只是剛好抽到分佈最右端。'
      '<br>佐證：539 與 F5 規則完全相同（pool 39、draw 5、同號域），只差一個 salt；'
      '若效果為真，F5 必須同時出現，但 F5 的 z = −0.17。'
      '<br>再佐證：T3 顯示排除區命中率<b>完全正常</b>（12.36% vs 理論 12.82%，p=0.75）。'
      '「排除區命中率正常」與「排除它們能提高命中率」不可能同時為真。</div>')

    A('<h3>② T4（539／F5）顯著 → 判定為 G3 高號保底的設計後果，非缺陷</h3>')
    A('<div class="scroll"><table><tr><th>彩種</th><th>線</th><th>χ²</th>'
      '<th>號 1–31 入選</th><th>高號入選</th><th>高號個數</th><th>最多/最少</th></tr>')
    for g in ("539", "f5", "m6"):
        for tag in ("S3", "B1"):
            d = dg[g]["D3_highLow"][tag]
            nm = "S3（現制）" if tag == "S3" else "B1（無規則）"
            cls = ' class="hl"' if tag == "S3" and d["p"] < 0.001 else ''
            A(f'<tr{cls}><td>{GN[g] if tag=="S3" else ""}</td><td>{nm}</td>'
              f'<td class="mono">{d["chi2"]:.1f}</td>'
              f'<td>{d["lowPct"]:.0f}%</td><td>{d["highPct"]:.0f}%</td>'
              f'<td>{d["nHigh"]}</td><td class="mono">{d["ratio"]:.2f}×</td></tr>')
    A('</table></div>')
    A('<div class="card"><b>判定</b>：<b>B1（關閉全部規則）在三彩種都完全均勻</b>'
      '（χ² = 7.2 / 5.2 / 17.2，p = 1.0000）→ PRNG 本身無偏，偏差全部來自規則。'
      '<br>機制：G3 要求 12 碼中至少 3 顆 ≥32。539/F5 的 pool=39，'
      '<b>≥32 只有 8 個號碼</b>要供應這 3 顆 ⇒ 高號入選率被推到均勻值的 132%。'
      '六合彩 pool=49、≥32 有 18 個號碼，壓力分散，因此 χ²=35 完全正常。'
      '<br><b>這不是 bug，是 G3 的直接數學後果，而且正是它的目的</b>——'
      '刻意偏離生日區 1–31 以降低撞號。T1 顯示這不影響命中率。'
      '建議把此數字寫進 <span class="mono">pick_engine.py</span> 註解，'
      '讓它成為「已知且刻意」而非「沒人算過」。</div>')

    # 漂移
    A('<h2>fpx-v3 失效與 fpx-v4</h2>')
    A('<div class="scroll"><table><tr><th>彩種</th><th>版本</th>'
      '<th>短窗（&lt;1000 期）</th><th>長窗（≥1000 期）</th><th>排除區命中率</th></tr>')
    for g in ("539", "f5", "m6"):
        a = st["games"][g]
        for tag, nm in (("S3", "fpx-v3（現行）"), ("S4", "fpx-v4（相對門檻）")):
            d = a[f"drift_{tag}"]
            t3 = a[f"T3_{tag}"]
            s, l = d["short"], d["long"]
            cls = ' class="hl"' if tag == "S4" else ''
            A(f'<tr{cls}><td>{GN[g] if tag=="S3" else ""}</td><td>{nm}</td>'
              f'<td>{s["avgSize"]:.2f} 顆／空 {s["zeroRate"]*100:.0f}%</td>'
              f'<td>{l["avgSize"]:.2f} 顆／空 {l["zeroRate"]*100:.0f}%</td>'
              f'<td class="mono">{pct(t3["rate"]) if t3["n"] else "—"}'
              f'（理論 {pct(t3["p0"])}）</td></tr>')
    A('</table></div>')
    A('<div class="card"><b>fpx-v3 隨歷史累積而失效</b>：'
      '<span class="mono">ATRISK_MIN=20</span> 是絕對門檻，歷史越長越深的柱子越容易達標，'
      '而深度 40+ 的柱子上幾乎不會有號碼 ⇒ 排除區趨向永遠為空。'
      '產線 <span class="mono">all_records</span> 只增不減，故此趨勢不可逆。'
      '<br><b>fpx-v4</b>（門檻改 <span class="mono">max(20, 5%×總樣本)</span>）'
      '讓排除區規模在長短窗下穩定。<b>但 T3 顯示 v3 與 v4 的排除區命中率都與理論無異</b>'
      '（六個檢定全部不顯著）—— 修好的是<b>穩定性</b>，不是<b>效果</b>。</div>')

    # ⚠️ 一段與本站無關的私人分析已於 2026-08-18 移出本檔（Fable 5 稽核）。
    #    ~/539 會 push 到公開 GitHub Pages，私人內容一律留在本機的私人目錄。

    # 效力
    A('<h2>效力分析（必讀）</h2>')
    A('<div class="warnbox">本回測可偵測的相對效果為 '
      '<b>539 ±2.04%、F5 ±1.90%、六合 ±3.39%</b>（2 SD，兌獎口徑）。<br>'
      '<b>因此，p &gt; 0.05 的正確講法是「排除了大於上述幅度的效果」，'
      '不是「證明沒有差異」。</b></div>')

    # 承諾
    A('<h2>預先承諾行動的執行</h2>')
    A('<div class="scroll"><table><tr><th>REGISTRY §5 條款</th><th>實際結果</th>'
      '<th>應執行</th></tr>')
    for cond, res, act in [
        ("T1 不顯著", "六個檢定全部不顯著",
         "✅ 維持現制，把數據寫進 pick_engine.py 註解"),
        ("T1 顯著正向 → 先查 bug", "T2（非 T1）出現顯著正向，已依同精神追查",
         "✅ 判定為 PRNG 偶然，不改制度"),
        ("T2/T3 顯示 v3 與 v4 皆與 B2 無異", "T3 六個檢定全部不顯著",
         "⚠️ 認定排除區無作用 → <b>評估直接廢除以簡化制度</b>"),
        ("T4 顯著 → 查是否 G2/G3 造成", "確認為 G3，且 B1 對照證明 PRNG 無偏",
         "✅ 非缺陷；建議寫入註解備查"),
        ("T5 顯著 → 查兌獎口徑或實作", "全部不顯著",
         "✅ 無須動作"),
    ]:
        A(f'<tr><td>{cond}</td><td>{res}</td><td>{act}</td></tr>')
    A('</table></div>')

    A('<div class="foot">產生：<span class="mono">backtest_report.py</span>　·　'
      '資料 <span class="mono">backtest_v3_results.json</span>／'
      '<span class="mono">backtest_v3_stats.json</span>／'
      '<span class="mono">backtest_v3_diagnostics.json</span>　·　'
      '事前註冊 <span class="mono">BACKTEST_REGISTRY.md</span><br>'
      '誠實揭露：期望值不因選號改變；歷史頻率不是勝率保證。</div>')
    A('</div>')

    html = ('<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8">'
            '<meta name="viewport" content="width=device-width,initial-scale=1">'
            f'<title>sfg-v3 回測報告</title><style>{CSS}</style></head><body>'
            + "\n".join(h) + '</body></html>')
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"→ 已寫入 {os.path.basename(OUT)}（{len(html)//1024} KB）")
    return OUT


if __name__ == "__main__":
    p = build()
    if "--open" in sys.argv:
        subprocess.run(["open", p])
